### PR TITLE
Demonstrate Cypress warnings 

### PR DESCRIPTION
**Pull request by kpturner**

### CODE REVIEW

**Comment by kpturner** [comment]
Run

`npm run test:open`

Run the only feature test available.  Look at the browser console output to see numerous examples

```
DevTools failed to load SourceMap: Could not load content for http://localhost:56575/__cypress/runner/popper.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
cypress_runner.js:179344 Cypress Warning: Cypress detected that you returned a promise in a test, but also invoked one or more cy commands inside of that promise.

The test title was:

  > Passing with TypeScript "before each" hook

While this works in practice, it's often indicative of an anti-pattern. You almost never need to return both a promise and also invoke cy commands.

Cy commands themselves are already promise like, and you can likely avoid the use of the separate Promise.

```

**Comment by lgandecki** [comment]
thanks for the reproduction. What if you don't use the cucumber preprocessor, but only pure cypress and try the same thing:

```
beforeEach(async () => {
    cy.log('beforeEach')
});
```

? I'm wondering whether this is related to our plugin at all

**Comment by kpturner** [comment]
Well it does not appear to happen with this example https://github.com/TheBrainFamily/cypress-cucumber-example
so it is perhaps just related to the Typescript example and the baggage that goes with that.

**Comment by lgandecki** [comment]
do we do beforeEach(async there? 
The Async keyword is what's most probably causing the issue. I don't think it's related neither to typescript or our plugin. That's why I wanted you to verify without it :)

**Comment by kpturner** [comment]
Ahh - sorry. I missed that subtlety.  Yes that addition of "async" causes it in all the cypress-cucumber-preprocessor examples so I will try without the preprocessor and post back here.

**Comment by kpturner** [comment]
Yep - it seems it happens in any project if you use the beforeEach hook and provide it with an async callback.
https://github.com/cypress-io/cypress/issues/3139
Sorry to have bothered you.

**Pull request closed without merging**
